### ISSUE TITLE
ValueError: Cannot take a larger sample than population when 'replace=False' 

### ISSUE THREAD

**Issue by cthomas-ann** [jaehyun513/STUNT#2]
Hi,
Thank you for sharing the code. 
I am getting this error after 1150 steps. Could you please help me with this?
Traceback (most recent call last):
	File "main.py", line 72, in <module>   
		main(0, P)  
	File "main.py", line 56, in main  
		meta_trainer(P, train_func, test_func, model, optimizer, train_loader, test_loader, logger) 
	File "STUNT/train/trainer.py", line 30, in meta_trainer 
		train_batch = next(train_loader)      
	File "STUNT/data/income.py", line 27, in __next__
		return self.get_batch()                
	File "STUNT/data/income.py", line 107, in get_batch 
		classes = np.random.choice(class_list, num_way, replace = False)   
	File "mtrand.pyx", line 965, in numpy.random.mtrand.RandomState.choice       
ValueError: Cannot take a larger sample than population when 'replace=False'

**Comment by jaehyun513** [comment]
Hello, thank you for sharing your issue with me. I understand that you are encountering an error when the length of the class list is smaller than the specified number of ways, which makes it impossible to randomly choose classes. This seems to occur when a smaller number of clusters is assigned.

One possible solution to this issue is to adjust the sampling ratio by increasing the number of random columns that are sampled. In our experiments, we have used a sampling ratio of 0.2 to 0.5, but it may be helpful to fine-tune this ratio in order to fix the error.

If you have any further questions or concerns, please do not hesitate to reach out to me. Thank you for your time.

**Comment by cthomas-ann** [comment]
> Hello, thank you for sharing your issue with me. I understand that you are encountering an error when the length of the class list is smaller than the specified number of ways, which makes it impossible to randomly choose classes. This seems to occur when a smaller number of clusters is assigned.
> 
> One possible solution to this issue is to adjust the sampling ratio by increasing the number of random columns that are sampled. In our experiments, we have used a sampling ratio of 0.2 to 0.5, but it may be helpful to fine-tune this ratio in order to fix the error.
> 
> If you have any further questions or concerns, please do not hesitate to reach out to me. Thank you for your time.

Thank you for the quick response. I will try the same and let you know the status.
